### ISSUE TITLE
How to create unittests for code that relies on `go-buildkite`?

### ISSUE THREAD

**Issue by migueleliasweb** [buildkite/go-buildkite#179]
Hi BK team,

are there any simplified way to test code that relies on `go-buildkite` other than injecting a custom `RoundTripper` to the underlying client transport?

For the `go-github` package, which apparently inspired this repo, there's a unittesting library built by the community called https://github.com/migueleliasweb/go-github-mock. Is there anything like it so unittesting is less painful?

**Comment by jradtilbrook** [comment]
Hi @migueleliasweb good question. `RoundTripper` is you best bet. We don't have plans to build out a unit testing helper suite with this at the moment, but we may in the future

**Comment by migueleliasweb** [comment]
That's a bit unfortunate.

Creating a unittest for code that uses the BuildkiteSDK in Golang and it's slightly more complex with many API calls, is extremely hard at the moment.

To be able to unittest something like that, the `RoundTripper` needs to be clever enough to understand multiple calls with multiple parameters. That requires a good amount of boilerplate.

I hope this gets addressed sooner other than later.

**Comment by moskyb** [comment]
hey friends - since this issue was closed, we've updated the library a fair bit. i agree that testing through an `http.RoundTripper` is super nasty, so i'm happy to say that we now support adding a custom endpoint to the client, which can then be used in concert with the [`httptest`](https://pkg.go.dev/net/http/httptest) library - indeed, it now powers most of the internal testing of this library. here's a slightly modified example i pulled from the tests - it should work on any 4.x version, and should work on later 3.x versions with a little modification.

```Go
func TestPackageUpload(t *testing.T) {
	t.Parallel()

	mux := http.NewServeMux()
	// Return a package with a known ID
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if err := json.NewEncoder(w).Encode(buildkite.Package{
			ID:   "package-id",
			Name: "test-package",
		}); err != nil {
			t.Fatalf("unexpected error encoding response: %v", err)
		}
	})

	server := httptest.NewServer(mux)
	client, err := buildkite.NewClient(buildkite.WithBaseURL(server.URL))
	if err != nil {
		t.Fatalf("unexpected NewOpts() error: %v", err)
	}

	cpi := buildkite.CreatePackageInput{
		Package:  bytes.NewBuffer([]byte("test")),
		Filename: "test-package",
	}
	pkg, _, err := client.PackagesService.Create(context.Background(), "my-org", "my-registry", cpi)
	if err != nil {
		t.Fatalf("Packages.Create returned error: %v", err)
	}

	// Do some useful stuff with pkg
}

```

i realise that depending on one's outlook, this is still maybe a lower-level mocking solution than might be ideal. it'd certainly be nice to just throw `gomock` at the problem and be done with it, but unfortunately the structure of this package - a god-struct whose members are all interfaces - makes this somewhat tricky. if you have some good ideas on improving this, i'd love to hear about them!
