### ISSUE TITLE
Team support

### ISSUE THREAD

**Issue by weirdtales** [buildkite/go-buildkite#24]
What are the plans for team support - is it being looked at?
Edit: obvs, this is a side glance at graphql

**Comment by lox** [comment]
As in REST endpoints for manipulating teams @weirdtales? We have it currently in the GraphQL api. No immediate plans to replicate it in the REST API, but it's potentially something we could look at.

**Comment by wolfeidau** [comment]
@lox Have you considered moving this to graphql? 

Is there coverage of all the existing REST calls in the GraphQL api?

**Comment by weirdtales** [comment]
@lox In the API would be great, but I mean for this package.

**Comment by lox** [comment]
> @lox Have you considered moving this to graphql?

@wolfeidau possibly, I'm still undecided how well GraphQL lends itself to thicker client libraries like this one. Ideally we'll end up with just a very thin GraphQL client and guidance on how to marshal and unmarshal whatever queries and mutations consumers require. Something as minimal as this is what we use elsewhere https://gist.github.com/lox/d97691970dbcc666b07b3d858a6fbb95

@weirdtales the issue is that at present the REST API doesn't have endpoints for team management. IMO it should. Might it be possible to raise a ticket in https://github.com/buildkite/feedback about your use-case and we'll see what we can do?

**Comment by weirdtales** [comment]
@lox https://github.com/buildkite/feedback/issues/412
