### ISSUE TITLE
Pointers in returned structs

### ISSUE THREAD

**Issue by chrissnell** [buildkite/go-buildkite#29]
[So many of the struct members](https://github.com/buildkite/go-buildkite/blob/master/buildkite/builds.go#L49-L92) that are returned by library calls are pointers.  This presents a messy problem for third-party software using the library, because we have to check for nil pointers before accessing struct members.  I see little advantage to using pointers here.  It adds a lot of ugly checks.  It's not a massive amount of data, so I think that it would be fine to just use regular data types, not pointers to data.

Thoughts?

**Comment by JensRantil** [comment]
I this issue is going to be worked on, I think #28 is a prerequisite before working on this.

As to why using pointers instead of values, the README states

> This project draws a lot of it's structure and testing methods from [go-github](https://github.com/google/go-github).

and https://github.com/google/go-github/issues/537#issue-204414025 and https://github.com/google/go-github/issues/79 give some insights into this decision.

**Comment by lox** [comment]
Yup, the AWS SDK uses this approach too. It's slightly gross, but allows nilable fields. I don't think we are likely to change this in the short term.
